📝 Add error manual error tracking documentation
DataDog/dd-sdk-flutter pull request #168
Opened 2022-07-14 21:51 UTC by fuzzybinary

### What and why?

We've had some clients ask about the state of Native Crash Reporting and desymbolication. I'd like to add these docs and somewhere to point them to while we work on the simplified / unified solution.

### Review checklist

- [ ] This pull request has appropriate unit and / or integration tests 
- [ ] This pull request references a Github or JIRA issue

### CI Configuration (optional)
- [ ] Run unit tests
- [ ] Run integration tests

2022-07-15 19:04 UTC, cswatt requested changes
leaving grammar edits

2022-07-15 19:04 UTC, cswatt commented on packages/datadog_flutter_plugin/docs/error_tracking.md
> +Update your initialization configuration to set `nativeCrashReportEnabled` to `true`
```suggestion
Update your initialization configuration to set `nativeCrashReportEnabled` to `true`.

For example:
```

2022-07-15 19:04 UTC, cswatt commented on packages/datadog_flutter_plugin/docs/error_tracking.md
> +This will enable native crash reporting for iOS and Android.
```suggestion
This enables native crash reporting for iOS and Android.
```

2022-07-15 19:04 UTC, cswatt commented on packages/datadog_flutter_plugin/docs/error_tracking.md
> +## Manually uploading Android Proguard Mapping Files to Datadog
```suggestion
## Manually upload Android ProGuard mapping files to Datadog
```

2022-07-15 19:04 UTC, cswatt commented on packages/datadog_flutter_plugin/docs/error_tracking.md
> +If you are using the `--obfuscate` parameter on Android builds, you will need to upload your Proguard mapping file to Datadog in order to deobfuscate your stack traces. The [Gradle Plugin for datadog
```suggestion
If you are using the `--obfuscate` parameter on Android builds, and you wish to deobfuscate your traces, you need to upload your ProGuard mapping file to Datadog. The [Gradle plugin for the Datadog Android SDK][1] supports uploading your mapping file directly to Datadog.
```

2022-07-15 19:04 UTC, cswatt commented on packages/datadog_flutter_plugin/docs/error_tracking.md
> +You can configure the plugin by adding the following to you `./android/app/build.gradle` file:
```suggestion
You can configure the plugin by adding the following lines to your `./android/app/build.gradle` file:
```

2022-07-15 19:04 UTC, cswatt commented on packages/datadog_flutter_plugin/docs/error_tracking.md
> +In addition, if you need to configure the upload, you can add the following block to the end of you `./android/app/build.gradle` file:
```suggestion
In addition, if you need to configure the upload, you can add the following block to the end of your `./android/app/build.gradle` file:
```

2022-07-15 19:04 UTC, cswatt commented on packages/datadog_flutter_plugin/docs/error_tracking.md
> +After building your Flutter application with `flutter build apk` or `flutter build appbundle`, use the following shell commands to upload your Mapping file to Datadog:
```suggestion
After building your Flutter application with `flutter build apk` or `flutter build appbundle`, use the following shell commands to upload your mapping file to Datadog:
```

2022-07-17 10:34 UTC, xgouchet approved these changes

2022-07-19 15:02 UTC, xgouchet approved these changes

2022-07-19 20:05 UTC, merged