👷 Add dependency_override removal to releaser
DataDog/dd-sdk-flutter pull request #214
Opened 2022-09-01 15:37 UTC by fuzzybinary

### What and why?

dependency_overrides are used during development to use local dependencies. But, when we go to deploy, we have to use non-local dependencies. This removes them before running the check for pub deploy.

### Review checklist

- [ ] This pull request has appropriate unit and / or integration tests 
- [ ] This pull request references a Github or JIRA issue

### CI Configuration (optional)
- [ ] Run unit tests
- [ ] Run integration tests

2022-09-01 18:16 UTC, jtappa requested changes
Small edits for consistency and grammar from docs team.

2022-09-01 18:16 UTC, jtappa commented on tools/releaser/README.md
> +After the release branch is finish building, you can deploy it with:
```suggestion
After the release branch is finished building, you can deploy it with:
```

2022-09-01 18:16 UTC, jtappa commented on tools/releaser/README.md
> +* Validates that `dart pub publish --dry-run` runs without errors.
```suggestion
* Validates that `dart pub publish --dry-run` runs without errors
```

2022-09-01 18:16 UTC, jtappa commented on tools/releaser/README.md
> +* Commit these changes to the chore branch to be merged back into develop.
```suggestion
* Commit these changes to the chore branch to be merged back into develop
```

2022-09-01 21:03 UTC, jtappa approved these changes

2022-09-02 06:42 UTC, xgouchet approved these changes

2022-09-02 06:53 UTC, 0xnm approved these changes

2022-09-02 17:54 UTC, merged