👩‍💻 Use already provided HttpOverrides when available
DataDog/dd-sdk-flutter pull request #428
Opened 2023-05-24 09:41 UTC by fuzzybinary

### What and why?

The `DatadogTrackingHttpClient` sets `HttpOverrides.global` without checking if client code has already overridden it. This can lead to unexpected behavior when clients need to use `HttpOverrides`.

I've also added more documentation to the library to make it clear what's happening.

See #424

### Review checklist

- [ ] This pull request has appropriate unit and / or integration tests 
- [x] This pull request references a Github or JIRA issue

### CI Configuration (optional)
- [x] Run unit tests
- [x] Run integration tests

2023-05-24 10:55 UTC, 0xnm approved these changes

2023-05-24 15:33 UTC, xgouchet approved these changes

2023-05-24 17:22 UTC, drichards-87 requested changes
Left you a minor piece of feedback from Docs.

2023-05-24 17:22 UTC, drichards-87 commented on packages/datadog_tracking_http_client/README.md
> +Note that the Datadog Tracking HTTP Client modifies [HttpOverrides.global](). If you need to provide your own `HttpOverrides`, make sure to initialize it prior to initializing Datadot. During initial
```suggestion
Note that the Datadog Tracking HTTP Client modifies `[HttpOverrides.global]()`. If you need to provide your own `HttpOverrides`, make sure to initialize it prior to initializing Datadog. During initialization, Datadog will check the value of `HttpOverrides.current` and use this for client creation if it exists.
```

2023-05-25 14:45 UTC, drichards-87 approved these changes

2023-05-26 07:44 UTC, merged