chore: Update develop with changes from release of 2.5.0
DataDog/dd-sdk-flutter pull request #606
Opened 2024-05-13 19:24 UTC by fuzzybinary

### What and why?

Changes related to releasing `datadog_flutter_plugin` 2.5.0

### Review checklist

- [ ] This pull request has appropriate unit and / or integration tests 
- [ ] This pull request references a Github or JIRA issue

2024-05-13 19:41 UTC, rtrieu requested changes
Some feedback for style consistency.

2024-05-13 19:41 UTC, rtrieu commented on packages/datadog_flutter_plugin/CHANGELOG.md
> +* Update iOS to 2.11.0. For a full list of changes see the [iOS Changelog](https://github.com/DataDog/dd-sdk-ios/blob/develop/CHANGELOG.md#2110--08-05-2024)
```suggestion
* Update iOS to 2.11.0. For a full list of changes, see the [iOS changelog](https://github.com/DataDog/dd-sdk-ios/blob/develop/CHANGELOG.md#2110--08-05-2024).
```

2024-05-13 19:41 UTC, rtrieu commented on packages/datadog_flutter_plugin/CHANGELOG.md
> +  * Add Fatal App hang tracking in RUM.
```suggestion
  * Add fatal app hang tracking in RUM.
```

2024-05-13 19:41 UTC, rtrieu commented on packages/datadog_flutter_plugin/CHANGELOG.md
> +  * Solve false-positive Privacy Manifest warnings on Required Reason API usage.
```suggestion
  * Solve false-positive privacy manifest warnings on Required Reason API usage.
```

2024-05-13 19:41 UTC, rtrieu commented on packages/datadog_flutter_plugin/CHANGELOG.md
> +  * Support calling log event mapper for crashes
```suggestion
  * Support calling log event mapper for crashes.
```

2024-05-13 19:41 UTC, rtrieu commented on packages/datadog_flutter_plugin/CHANGELOG.md
> +  * Support calling log event mapper for crashes
```suggestion
  * Support calling log event mapper for crashes.
```

2024-05-14 12:48 UTC, 0xnm submitted a review, later dismissed

2024-05-14 12:48 UTC, 0xnm commented on packages/datadog_flutter_plugin/CHANGELOG.md
> +  * Support calling log event mapper for crashes.
this was there since 2.0.0.

2024-05-14 12:57 UTC, fuzzybinary commented on packages/datadog_flutter_plugin/CHANGELOG.md
> +  * Support calling log event mapper for crashes.
Both or just the logger?

2024-05-14 13:04 UTC, 0xnm commented on packages/datadog_flutter_plugin/CHANGELOG.md
> +  * Support calling log event mapper for crashes.
only for logger

2024-05-14 13:59 UTC, 0xnm approved these changes

2024-05-14 17:27 UTC, rtrieu approved these changes
LGTM

2024-05-14 18:10 UTC, merged