chore: add ignoreUrlPatterns to TrackingExtensionExisting
DataDog/dd-sdk-flutter pull request #613
Opened 2024-05-23 20:02 UTC by 4rthurmonteiro

### What and why?

To filter http tracking when using Flutter module.

What changes does this pull request introduce and why is it necessary?

Add ignoreUrlPatterns to TrackingExtensionExisting extension

### How?

Adding in enableHttpTracking the attribute ignoreUrlPatterns.

If needed, a description of how this PR accomplishes what it does.

### Review checklist

- [ ] This pull request has appropriate unit and / or integration tests 
- [ ] This pull request references a Github or JIRA issue

2024-05-23 20:50 UTC, 4rthurmonteiro commented
@fuzzybinary  why did bitrise check fail?

2024-05-24 18:13 UTC, fuzzybinary commented
@4rthurmonteiro It doesn't run unless we approve it for security reasons.

2024-05-24 18:18 UTC, fuzzybinary commented on examples/native-hybrid-app/flutter_module/lib/main.dart
> +      // Using ignoreUrlPatterns is needed if you want to combine HttpClient
I'm not sure what you're trying to say with this comment?

`ignoreUrlPatterns` should be optional, and really should only used if you don't want to track requests to a specific URL (usually because it's tracked with something else, like the gRPC interceptor).

2024-05-24 18:19 UTC, fuzzybinary commented
also nit: this is a feature, not a chore.

2024-05-24 18:25 UTC, 4rthurmonteiro commented on examples/native-hybrid-app/flutter_module/lib/main.dart
> +      // Using ignoreUrlPatterns is needed if you want to combine HttpClient
Can I just copy the same comment from the other sample? @fuzzybinary

2024-05-24 18:25 UTC, 4rthurmonteiro commented
> also nit: this is a feature, not a chore.

changed!

2024-05-24 20:31 UTC, fuzzybinary commented on examples/native-hybrid-app/flutter_module/lib/main.dart
> +      // Using ignoreUrlPatterns is needed if you want to combine HttpClient
Yes, you missed the second line of it in the copy which is why it didn't make sense.

2024-05-24 21:08 UTC, 4rthurmonteiro commented
@fuzzybinary i updated the example.

2024-05-28 15:28 UTC, fuzzybinary approved these changes

2024-05-28 15:31 UTC, fuzzybinary requested changes
@4rthurmonteiro Sorry a few more minor requests. 

First, We require [all commits to be signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification). Would you be able to do that and re-open? If not I can make the changes and get them in.

Second, can you add an item to the [CHANGELOG](https://github.com/DataDog/dd-sdk-flutter/blob/develop/packages/datadog_tracking_http_client/CHANGELOG.md)?

2024-05-28 15:31 UTC, fuzzybinary commented on packages/datadog_tracking_http_client/test/datadog_tracking_http_client_test.dart
> +import 'package:datadog_tracking_http_client/datadog_tracking_http_client.dart';
Apparently this import is unused....

2024-05-28 18:14 UTC, 4rthurmonteiro commented
> @4rthurmonteiro Sorry a few more minor requests.
> 
> First, We require [all commits to be signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification). Would you be able to do that and re-open? If not I can make the changes and get them in.
> 
> Second, can you add an item to the [CHANGELOG](https://github.com/DataDog/dd-sdk-flutter/blob/develop/packages/datadog_tracking_http_client/CHANGELOG.md)?

Ok, i will reopen. Thanks @fuzzybinary

2024-05-28 19:19 UTC, closed without merging